### ISSUE TITLE
Support for current Ubuntu LTS release 20.04 was dropped in a patch version bump

### ISSUE THREAD

**Issue by adamnovak** [anko/tests-ex-markdown#7]
In 7.4.6, txm updated to yargs 17, which dropped support for Node 10. The current Ubuntu LTS release still ships Node 10. This has caused txm to no longer work on the current Ubuntu LTS release, and the next Ubuntu LTS release with an updated Node is not yet available.

If dropping support for a release of Node, especially an important one like the one that Ubuntu's current LTS release is using, the package ought to release a new major version, so install scripts using `npm install txm@7`, or packages depending on `^7`, will not have support for current Ubuntu LTS (or a Node version in general) removed due to a new release of txm appearing.

**Comment by anko** [comment]
This is an interesting edge case of [Semantic Versioning](https://semver.org/) that I hadn't considered, and which the semver spec is silent on.  If a change breaks on an old version of the platform (here: Node), is that an "incompatible API change"?  If so, does that mean I must test every change against every version of Node from 0.1.x (2011) til today, and increment the major version number if any of them break?  If not, how far back counts?

I suppose the semver spec's silence means it's up to each project to declare what range of platform version support is part of its public interface, and it hasn't come up yet for txm, so it has been undefined.

So, to define it:  txm targets OpenJS Foundation's *Active LTS* version of Node, which [is currently](https://nodejs.org/en/about/releases/) 16.  I've been doing that so far, silently assuming it's what most users would expect.  Versions will be marked with that assumption.  I should document that somewhere in the readme for clarity.  I might extend that to *Maintenance LTS* also in the future, if I can get Github Actions to be less of a pain in the neck regarding Node version aliases for automated tests.

- - -

Do note that the OJSF doesn't fix critical Node bugs for anything older than Node 12 anymore.  Newer binaries [are available](https://nodejs.org/en/about/releases/) regardless of what version your distribution packages.  If you want a deb package, [NodeSource maintains package repositories with modern Node versions, also for Ubuntu 20.04 LTS](https://github.com/nodesource/distributions/blob/master/README.md#deb).  I would find it very unusual if _any_ project bumped their major version number just because they broke an abandoned Node version.

**Comment by adamnovak** [comment]
I think the real blame here lies with Ubuntu or maybe Debian upstream node packagers. Presumably they're volunteering to backport or do their own security fixes to the node versions they ship, if they ship them past when upstream Node supports them but still support those OS releases. But then they're essentially shipping a fork of Node that the Node community has moved on from. Great for running Node scripts that don't use any modules, or get all their modules form the distro package manager, and maybe for running hypothetical user-facing packaged apps that run on Node, but not actually useful for real-world Node use cases.

And I can't imagine that all the distro-packaged Node modules are actually getting security patches backported in a timely manner.

See rant at https://bugs.launchpad.net/ubuntu/+source/nodejs/+bug/1861327

**Comment by anko** [comment]
I've added an `engines` field to `package.json`, so `npm install txm` should now show a helpful warning if the local Node version is unsupported.  CI is back up, and tracking Active LTS.
