### ISSUE TITLE
txm demands that the current directory have a `package.json`

### ISSUE THREAD

**Issue by adamnovak** [anko/tests-ex-markdown#8]
I use txm to test documentation for a non-Node project. Recently (as of 8.0.0?) it has started complaining that it can't open `package.json` when run on my project's Markdown files. 7.4.5 worked fine.

```
txm --jobs 1 /Users/runner/work/vg/vg/doc/../README.md
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './package.json'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at file:///usr/local/lib/node_modules/txm/src/main.js:12:33
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './package.json'
}
```

I think this is intending to read *txm*'s package.json, but it ends up just looking in the current directory when the code is run.
https://github.com/anko/txm/blob/1b0cd9619a8a2b9a22e21d6c622aeb2077f46fe6/src/main.js#L12

**Comment by anko** [comment]
Oops.  Thanks for reporting!  Fixed in https://github.com/anko/txm/commit/545b55db1e7bfa58102803adf1ccb626a6123533, published in [8.0.1](https://www.npmjs.com/package/txm/v/8.0.1).

> I think this is intending to read txm's package.json, but it ends up just looking in the current directory when the code is run.

This was correct.  More post-mortem details in the commit message. In short, I made mistakes in ESM conversion, and a string of coincidences caused my previous tests to show false positives.
